// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STP.Profile.Persistence.Context;

namespace STP.Profile.Persistence.Migrations
{
    [DbContext(typeof(ProfileDbContext))]
    [Migration("20190730105122_migration1")]
    partial class migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("STP.Profile.Domain.Entities.OrderEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Action");

                    b.Property<long>("MarketId");

                    b.Property<double>("Price");

                    b.Property<int>("Quantity");

                    b.Property<DateTime>("Timestamp");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("STP.Profile.Domain.Entities.PositionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("AveragePrice");

                    b.Property<long>("EntryOrderId");

                    b.Property<long>("ExitOrderId");

                    b.Property<int>("Kind");

                    b.Property<long>("MarketId");

                    b.Property<double>("ProfitLoss");

                    b.Property<long>("Quantity");

                    b.Property<DateTime>("Timestamp");

                    b.Property<double>("UnrealizedProfitLoss");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.ToTable("position");
                });
#pragma warning restore 612, 618
        }
    }
}
